name: my-hyprland-os
description: Custom ublue-os base with Hyprland
base-image: ghcr.io/ublue-os/base-main
image-version: latest

modules:
  # 0. Enable COPR for Hyprland extras
  - type: script
    scripts:
      - enable_copr.sh

  # 1. Install RPM Packages
  - type: rpm-ostree
    install:
      # --- Core & Shell ---
      - git
      - wget
      - aria2
      - tmux
      - zsh
      - zsh-autosuggestions
      - zsh-syntax-highlighting
      - vim-enhanced
      - htop
      - distrobox
      - fastfetch
      - jq
      - parallel
      
      # --- Hyprland Ecosystem ---
      - hyprland
      - hyprpaper
      - hyprlock
      - hypridle
      - hyprland-qtutils
      - waybar
      - rofi-wayland
      - swaync
      - wlogout
      - grim
      - slurp
      - wl-clipboard
      - swappy
      - cliphist
      - nwg-displays
      - nwg-look
      - lxpolkit
      - network-manager-applet
      - blueman
      
      # --- Theming/Qt ---
      - sddm
      - adwaita-gtk2-theme
      - adwaita-icon-theme
      - adw-gtk3-theme
      - qt5-qtstyleplugins
      - gnome-themes-extra
      - bibata-cursor-themes
      - abattis-cantarell-fonts
      - qt5-qtgraphicaleffects
      - qt5-qtquickcontrols2
      - qt5-qtsvg
      - qt5ct
      - qt6ct
      - kvantum
      
      # --- Networking ---
      - tailscale

      # --- GUI Applications ---
      - xarchiver
      - gnome-text-editor
      - gnome-calculator
      - mpv
      - eog            
      - pavucontrol
      - brightnessctl
      - playerctl
      - pamixer
      - yad

      # --- Missing Dependencies (Added for base-main) ---
      - nautilus
      - gvfs
      - gvfs-mtp # Android phone file transfer
      - gvfs-smb # Network file sharing (SMB/CIFS)
      - gnome-keyring
      - kitty
      - polkit
      - xdg-user-dirs # Standardizes /home folders (Downloads, Pictures, etc.)

      # --- Portals (Critical for Hyprland/Flatpaks) ---
      - xdg-desktop-portal-hyprland # Screen sharing, recording, Wayland features
      - xdg-desktop-portal-gtk # Fallback file picker and theme integration

      # --- Archives & Thumbnails ---
      - unzip
      - zip
      - p7zip
      - p7zip-plugins # Handles .rar extraction (replacing unrar)
      - tar
      - xz
      - bzip2
      - gzip
      - ffmpegthumbnailer # Video thumbnails in Nautilus

      # --- Codecs & Multimedia ---
      - gstreamer1-plugins-ugly-free
      - gstreamer1-plugins-bad-free-extras
      - gstreamer1-vaapi # Hardware acceleration
      # Note: Full ffmpeg requires RPM Fusion, not added here to keep it pure Fedora for now

      # --- Fonts (Base & Emojis) ---
      - google-noto-emoji-fonts # Fixes broken emojis in apps
      - rsms-inter-fonts # Modern UI font
      
      # Sound
      - pipewire
      - wireplumber
      - pipewire-alsa
      - pipewire-pulseaudio
      - pipewire-utils # CLI tools (pw-top, etc.)

      # Network/Bluetooth
      - NetworkManager
      - NetworkManager-tui
      - NetworkManager-wifi
      - bluez
      - bluez-cups

      # --- HDD / SSD tool
      - smartmontools

  # 2. Copy Config Files
  - type: files
    files:
      - source: system
        destination: /

  # 3. Flatpak Configuration
  - type: default-flatpaks
    configurations:
      - container: system
        notify: true
        install:
          - com.github.tchx84.Flatseal
          - net.waterfox.waterfox

  # 4. Fonts
  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono

  # 5. Systemd Services
  - type: systemd
    system:
      enabled:
        - tailscaled
        - sddm
        - NetworkManager
        - bluetooth

  # 6. Customize OS Name
  - type: os-release
    properties:
      NAME: "GalihOS"
      PRETTY_NAME: "GalihOS (ublue-os with hyprland) x86_64"
      ID: "galihos"
      ID_LIKE: fedora
      VERSION_ID: "2.0"
      VARIANT: "Hyprland Edition"
      VARIANT_ID: "hyprland"
      DEFAULT_HOSTNAME: "GalihOS"

  - type: signing
