name: my-hyprland-os
description: Custom ublue-os base with Hyprland
base-image: ghcr.io/ublue-os/base-main
image-version: latest

modules:
  # 1. Enable RPM Fusion (Insert this FIRST)
  # This provides access to non-free codecs and full ffmpeg
  - type: rpm-fusion
    cisco-h264:
      enabled: true
    nonfree:
      enabled: true

  # 2. Enable COPR for Hyprland extras
  - type: script
    scripts:
      - enable_copr.sh

  # 3. Install RPM Packages
  - type: rpm-ostree
    install:
      # --- Core & Shell ---
      - git # Version control
      - wget # File downloader
      - aria2 # Lightweight download utility
      - tmux # Terminal multiplexer
      - zsh # Z Shell
      - zsh-autosuggestions # Zsh history suggestions
      - zsh-syntax-highlighting # Zsh syntax highlighting
      - vim-enhanced # Advanced Vim editor
      - htop # Process viewer
      - distrobox # Container management
      - fastfetch # System info tool
      - jq # JSON processor
      - parallel # Parallel job executor
      
      # --- Hyprland Ecosystem ---
      - hyprland # Wayland compositor
      - hyprpaper # Wallpaper utility
      - hyprlock # Screen locker
      - hypridle # Idle daemon
      - hyprland-qtutils # Qt/Hyprland integration
      - waybar # Status bar
      - rofi-wayland # App launcher
      - swaync # Notification daemon
      - wlogout # Logout menu
      - grim # Screenshot tool
      - slurp # Screen region selector
      - wl-clipboard # Clipboard utilities
      - swappy # Screenshot annotation
      - cliphist # Clipboard history
      - nwg-displays # Monitor configuration
      - nwg-look # GTK theme customization
      - lxpolkit # PolicyKit authentication agent
      - network-manager-applet # Network tray icon
      - blueman # Bluetooth manager
      
      # --- Theming/Qt ---
      - sddm # Login manager
      - adwaita-gtk2-theme # GTK2 theme
      - adwaita-icon-theme # Standard icon theme
      - adw-gtk3-theme # Libadwaita theme for GTK3
      - qt5-qtstyleplugins # Qt style plugins
      - gnome-themes-extra # Extra GNOME themes
      - bibata-cursor-themes # Modern cursor theme
      - abattis-cantarell-fonts # GNOME default font
      - qt5-qtgraphicaleffects # Qt graphical effects
      - qt5-qtquickcontrols2 # Qt Quick Controls 2
      - qt5-wayland # Necessary for Qt5 apps to run natively on Wayland (fixes blurry apps)
      - qt6-wayland # Necessary for Qt6 apps to run natively on Wayland
      - qt5-qtsvg # Qt SVG support
      - qt5ct # Qt5 configuration tool
      - qt6ct # Qt6 configuration tool
      - kvantum # Qt SVG theme engine
      
      # --- Networking ---
      - tailscale # Mesh VPN

      # --- GUI Applications ---
      - xarchiver # Archive manager
      - gnome-text-editor # Simple text editor
      - gnome-calculator # Calculator
      - mpv # Media player
      - eog # Image viewer (Eye of GNOME)
      - pavucontrol # PulseAudio volume control
      - brightnessctl # Brightness control CLI
      - playerctl # Media player control CLI
      - pamixer # PulseAudio mixer CLI
      - yad # GUI dialog tool for scripts

      # --- Missing Dependencies (Added for base-main) ---
      - nautilus # File manager
      - gvfs # Virtual filesystem
      - gvfs-mtp # Android MTP support
      - gvfs-smb # SMB/CIFS support
      - gnome-keyring # Password manager
      - kitty # Terminal emulator
      - polkit # Privilege management
      - xdg-user-dirs # User directory manager

      # --- Portals (Critical for Hyprland/Flatpaks) ---
      - xdg-desktop-portal-hyprland # Hyprland portal
      - xdg-desktop-portal-gtk # GTK portal fallback

      # --- Archives & Thumbnails ---
      - unzip # Zip extractor
      - zip # Zip archiver
      - p7zip # 7z archiver
      - p7zip-plugins # Rar support
      - tar # Tarball utility
      - xz # XZ compression
      - bzip2 # Bzip2 compression
      - gzip # Gzip compression
      - ffmpegthumbnailer # Video thumbnailer

      # --- Codecs & Multimedia ---
      - gstreamer1-plugins-ugly-free # Multimedia codecs
      - gstreamer1-plugins-bad-free-extras # Extra multimedia codecs
      - ffmpeg # The full ffmpeg package from RPM Fusion
      - gstreamer1-plugin-openh264 # Enables H.264 video playback support via Cisco's binary (fallback/legal)
      - gstreamer1-vaapi # Enables Hardware Acceleration for GStreamer applications to reduce CPU usage
      - intel-media-driver # Install intel VAAPI drivers to reduce CPU usage
      
      # --- Fonts (Base & Emojis) ---
      - google-noto-emoji-fonts # Emoji fonts
      - rsms-inter-fonts # Inter UI font
      - google-noto-sans-cjk-fonts # Essential for Japanese/Chinese characters
      
      # Sound
      - pipewire # Audio/Video server
      - wireplumber # PipeWire session manager
      - pipewire-alsa # ALSA compatibility
      - pipewire-pulseaudio # PulseAudio compatibility
      - pipewire-utils # PipeWire CLI tools

      # Network/Bluetooth
      - NetworkManager # Network connection manager
      - NetworkManager-tui # NMTUI text interface
      - NetworkManager-wifi # WiFi support
      - bluez # Bluetooth stack
      - bluez-cups # Bluetooth printing

      # --- HDD / SSD tool
      - smartmontools # Disk health monitoring

      # CLI screen recorder
      - wf-recorder # A utility program for screen recording
      - slurp # slurp allows you to select a specific region of the screen to record

  # 3. Copy Config Files
  - type: files
    files:
      - source: system
        destination: /

  # 4. Flatpak Configuration
  - type: default-flatpaks
    configurations:
      - container: system
        notify: true
        install:
          - com.github.tchx84.Flatseal
          - net.waterfox.waterfox

  # 5. Fonts
  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono

  # 6. Systemd Services
  - type: systemd
    system:
      enabled:
        - tailscaled
        - sddm
        - NetworkManager
        - bluetooth
        - rpm-ostreed-automatic.timer

  # 7. Customize OS Name
  - type: os-release
    properties:
      NAME: "GalihOS"
      PRETTY_NAME: "GalihOS (ublue-os with hyprland) x86_64"
      ID: "galihos"
      ID_LIKE: fedora
      VERSION_ID: "2.0"
      VARIANT: "Hyprland Edition"
      VARIANT_ID: "hyprland"
      DEFAULT_HOSTNAME: "GalihOS"

  - type: signing
