# recipes/recipe.yml
name: my-hyprland-os
description: Custom Wayblue with Zsh, Vim, Waterfox, and Tailscale
base-image: ghcr.io/wayblueorg/hyprland
image-version: latest

modules:
  # 1. Install RPM Packages
  - type: rpm-ostree
    install:
      # --- Core & Shell ---
      - git
      - wget
      - aria2
      - tmux
      - zsh
      - vim-enhanced
      - htop
      - distrobox
      - fastfetch
      
      # --- Networking ---
      - tailscale

      # --- GUI Applications ---
      # Wayblue has the basics, adding your specific tools:
      - xarchiver
      - gnome-text-editor
      - gnumeric
      - gnome-calculator
      - mpv
      - eog            

      # --- HDD / SSD tool
      - smartmontools

  # 2. Copy Config Files (Your Dotfiles)
  - type: files
    files:
      - source: system
        destination: /

  # 3. Flatpak Configuration
  - type: default-flatpaks
    configurations:
      - container: system
        notify: true
        install:
          - com.github.tchx84.Flatseal
          - net.waterfox.waterfox

  # 4. Systemd Services (Enable Tailscale automatically)
  - type: systemd
    system:
      enabled:
        - tailscaled

  - type: signing
