# recipes/recipe.yml
name: my-hyprland-os
description: Custom Silverblue with Hyprland, Zsh, and Vim
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

modules:
  # 1. Add Third-Party Repositories
  - type: rpm-ostree
    repos:
      # Solopasha Hyprland (Recommended for bleeding edge Hyprland on Fedora)
      - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%OS_VERSION%/solopasha-hyprland-fedora-%OS_VERSION%.repo

    # 2. Install RPM Packages
    install:
      # --- Core & Shell ---
      - git
      - wget
      - aria2
      - tmux
      - zsh
      - vim-enhanced
      - htop
      - distrobox
      
      # --- Hyprland Ecosystem ---
      - hyprland
      - hypridle
      - hyprpaper
      - rofi
      - kitty
      - network-manager-applet
      
      # --- GUI Applications (Layered RPMs) ---
      - flatpak
      - thunar
      - xarchiver
      - pavucontrol
      - gnome-text-editor
      - gnumeric
      - gnome-calculator
      - mpv
      - eog            # Image Viewer (Eye of Gnome)

      # --- HDD / SSD tool
      - smartmontools

  # 4. Copy Config Files (Your Dotfiles)
  - type: files
    files:
      - source: system
        destination: /

  # 5. Flatpak Configuration (Enables Flathub)
  # This module configures the 'flatpak' engine we installed above to use Flathub.
  # 5. Flatpak Configuration
  - type: default-flatpaks
    configurations:
      - container: system
        notify: true
        install:
          - com.github.tchx84.Flatseal
          - net.waterfox.waterfox

  - type: signing
