# recipes/recipe.yml
name: my-hyprland-os
description: Custom Silverblue with Hyprland (replacing GNOME)
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

modules:
  # 0. Enable COPR for Hyprland extras
  - type: script
    scripts:
      - enable_copr.sh

  # 1. Install RPM Packages
  - type: rpm-ostree
    # Remove GNOME bits to "de-gnome" the image
    remove:
      - firefox # Replacing with Waterfox (Flatpak)
      - firefox-langpacks
      - gdm # Replacing with SDDM
      - gnome-initial-setup # Depends on GDM
      - gnome-shell
      - gnome-shell-extension-common # Depends on gnome-shell
      - gnome-shell-extension-background-logo
      - gnome-shell-extension-window-list
      - gnome-browser-connector
      - gnome-software
      - ptyxis # Replacing with Kitty
    
    install:
      # --- Core & Shell ---
      - git
      - wget
      - aria2
      - tmux
      - zsh
      - vim-enhanced
      - htop
      - distrobox
      - fastfetch
      - jq
      - parallel
      
      # --- Hyprland Ecosystem ---
      - hyprland
      - hyprpaper
      - hyprlock
      - hypridle
      - waybar
      - rofi-wayland
      - swaync
      - wlogout
      - grim
      - slurp
      - wl-clipboard
      - swappy
      - cliphist
      - nwg-displays
      - nwg-look
      - lxpolkit
      - network-manager-applet
      - blueman
      - swww # From COPR
      
      # --- Theming/Qt ---
      - sddm
      - qt5-qtgraphicaleffects
      - qt5-qtquickcontrols2
      - qt5-qtsvg
      - qt5ct
      - qt6ct
      - kvantum
      
      # --- Networking ---
      - tailscale

      # --- GUI Applications ---
      - xarchiver
      - gnome-text-editor
      - gnumeric
      - gnome-calculator
      - mpv
      - eog            
      - pavucontrol
      - brightnessctl
      - playerctl
      - pamixer
      - yad

      # --- HDD / SSD tool
      - smartmontools

  # 2. Copy Config Files
  - type: files
    files:
      - source: system
        destination: /

  # 3. Flatpak Configuration
  - type: default-flatpaks
    configurations:
      - container: system
        notify: true
        install:
          - com.github.tchx84.Flatseal
          - net.waterfox.waterfox

  # 4. Systemd Services
  - type: systemd
    system:
      enabled:
        - tailscaled
        - sddm
      disabled:
        - gdm

  # 5. Customize OS Name
  - type: os-release
    properties:
      NAME: "Fedora Linux"
      PRETTY_NAME: "GalihOS (Silverblue Hyprland) x86_64"
      ID: "galihos"
      VERSION_ID: "2.0"
      VARIANT: "Hyprland Edition"
      VARIANT_ID: "hyprland"
      DEFAULT_HOSTNAME: "GalihOS"

  - type: signing