# recipes/recipe.yml
name: GalihOS
description: Custom Wayblue with Zsh, Vim, Waterfox, and Tailscale
base-image: ghcr.io/wayblueorg/hyprland
image-version: latest

modules:
  # 1. Install RPM Packages
  - type: rpm-ostree
    install:
      # --- Core & Shell ---
      - git
      - wget
      - aria2
      - tmux
      - zsh
      - vim-enhanced
      - htop
      - distrobox
      - fastfetch
      
      # --- Networking ---
      - tailscale

      # --- GUI Applications ---
      - xarchiver
      - gnome-text-editor
      - gnumeric
      - gnome-calculator
      - mpv
      - eog            

      # --- HDD / SSD tool
      - smartmontools

  # 2. Copy Config Files
  - type: files
    files:
      - source: system
        destination: /

  # 3. Flatpak Configuration
  - type: default-flatpaks
    configurations:
      - container: system
        notify: true
        install:
          - com.github.tchx84.Flatseal
          - net.waterfox.waterfox

  # 4. Systemd Services
  - type: systemd
    system:
      enabled:
        - tailscaled

  # 5. Customize OS Name (Add this block!)
  - type: os-release
    name: GalihOS
    id: galihos
    version-id: "1.0"
    variant: "Hyprland Edition"
    variant-id: hyprland

  - type: signing
